
name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Npm Security Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencios
      run: npm install
    - name: Run Tests
      run: npm test
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test-npm-security

  Build and Integration Tests:
    runs-on: ubuntu-latest
    needs: Npm Srcurity Test
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencios
      run: npm install
    - name: Run Tests
      run: npm test
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
