
name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Npm_Security_Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm test
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test-npm-security

  Build_and_Integration_Tests:
    runs-on: ubuntu-latest
    needs: Npm_Security_Test
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm test
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  Deploy_Application:

    jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.srv-cphqg9sf7o1s73b7v28g }}
          wait-for-success: true